# Generated by Django 5.2.8 on 2025-11-17 20:06

from django.utils import timezone
from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if User.objects.exists():
        return 
    
    superuser = User.objects.create_superuser(
        username="exampler_username",
        email="example@example.com",
        password="example@password",
        last_login=timezone.now()
    )
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_word_count'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
